WebAppNetCore/Pages/EntriesManager.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Security.Cryptography.X509Certificates;
using System.Xml;
using MongoDB.Driver;
using WebAppNetCore.wwwroot.Models.DataModel;
using System.Text;
using System.Xml.Linq;
using MongoDB.Bson;

namespace WebAppNetCore.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }
        
        public void OnGet()
        {
            
        }
        public RedirectToActionResult OnPostDoWork()
        {
            var inpString = HttpContext.Request.Form["userInput"];
            var inpData = HttpContext.Request.Form["userData"];
            var builder = new ConfigurationBuilder();
            builder.AddJsonFile("appsettings.Development.json");

            IConfiguration configuration = builder.Build();
            var constring = configuration["MyDatabaseSettings:ConnectionString"];
            var client = new MongoClient(constring);
            var database = client.GetDatabase("AMLDatabase");
            var data = new DataModel();
            IMongoCollection<DataModel> collection;
            if(database.GetCollection<DataModel>(inpString).CountDocuments(_ => true) > 0)
            {
                collection = database.GetCollection<DataModel>(inpString);
                var filter = Builders<DataModel>.Filter.Eq("Name", "firstString");
                var update = Builders<DataModel>.Update.Set("Data", PrettyXml(inpData));
                collection.UpdateOne(filter,update);
            }
            else
            {
                database.CreateCollectionAsync(inpString);
                collection = database.GetCollection<DataModel>(inpString);
                data.Name = "firstString";
                data.Data = PrettyXml(inpData);
                collection.InsertOneAsync(data);

            }
            System.Diagnostics.Debug.WriteLine(inpString + "\n" + PrettyXml(inpData));
            return RedirectToAction("Index");
            
        }
        static string PrettyXml(string rawStringxml)
        {
            XmlDocument xmlDoc = new XmlDocument();
            StringWriter sw = new StringWriter();
            xmlDoc.LoadXml(rawStringxml);
            xmlDoc.Save(sw);
            String formattedXml = sw.ToString();

            return formattedXml;
        }
    }
}

WebAppNetCore/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace WebAppNetCore.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

WebAppNetCore/Pages/Index.cshtml.cs
using Amazon.Runtime.Documents;
using Microsoft.AspNetCore.Html;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Razor.TagHelpers;
using MongoDB.Bson.Serialization.Attributes;
using MongoDB.Driver;
using System.Buffers;
using System.Reflection.Metadata;
using System.Runtime.CompilerServices;
using System.Security.Cryptography.X509Certificates;
using System.Text.Encodings.Web;
using System.Web;
using Microsoft.Extensions.Configuration;
using WebAppNetCore.wwwroot.Models.DataModel;


namespace WebAppNetCore.Pages
{

    public class IndexModel : PageModel
    {
        public string CollectionData { get; set; }

        private readonly ILogger<IndexModel> _logger;


        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }
        public void OnGet()
        {
        }
        public async void OnPostNameChange()
        {
            var inpString = HttpContext.Request.Form["userData"];
            System.Diagnostics.Debug.WriteLine(inpString);
            var data = await DataAsync(inpString);

            CollectionData = data.ToString();
            System.Diagnostics.Debug.WriteLine(data);
        }


        // Requesting data from database and parsing it to invisible <a> tag to use it in js.
        public async Task<string> DataAsync(string collectionName)
        {

            var builder = new ConfigurationBuilder();
            builder.AddJsonFile("appsettings.Development.json");

            IConfiguration configuration = builder.Build();
            var constring = configuration["MyDatabaseSettings:ConnectionString"];

            string res = "";


            var client = new MongoClient(constring);
            var db = client.GetDatabase("AMLDatabase");
            IMongoCollection<DataModel> collection; 
            try
            {
                collection = db.GetCollection<DataModel>(collectionName);
            }
            catch
            {
                collection = db.GetCollection<DataModel>("XmlStrings");
            }
            

            var results = await collection.FindAsync<DataModel>(_ => true);
            foreach (var result in results.ToList())
            {
                if (result.Data != null)
                {
                    res = result.Data;

                }

            }


            return res;
        }
    }







}

WebAppNetCore/Pages/EntriesManager.cshtml
@page
@using System.Xml
@using Microsoft.AspNetCore.Http.Extensions
@using Newtonsoft.Json
@using MongoDB.Driver
@using Microsoft.Extensions.Configuration;
@using WebAppNetCore.wwwroot.Models.DataModel
@using Microsoft.AspNetCore.Mvc.TagHelpers;

@inject IAntiforgery antiforgery;
@model PrivacyModel

@{
    ViewData["Title"] = "Entries Manager";
    var token = antiforgery.GetAndStoreTokens(HttpContext).RequestToken;
    var interfaces = await GetInterfaces();
   



}


@{


    async Task<string> GetInterfaces()
    {

        var builder = new ConfigurationBuilder();
        builder.AddJsonFile("appsettings.Development.json");

        IConfiguration configuration = builder.Build();
        var constring = configuration["MyDatabaseSettings:ConnectionString"];

        var client = new MongoClient(constring);
        var db = client.GetDatabase("Interfaces_Database");

        var collection = db.GetCollection<DataModel>("Base_Interface_Library");
        var value = collection.Find<DataModel>(_ => true);
        var result = "";
        foreach (var i in value.ToList())
        {
            result += i.Data;
        }

        return result;

    }
}


<h1>@ViewData["Title"]</h1>
<head>
    <!-- Entry manager script  -->
    <script src="~/lib/jquery/dist/jquery.min.js"></script>

    <script src="~/js/EntryManager.js"></script>
    <script src="~/js/xmlwriter/XMLWriter.js"></script>

</head>
<h4>Use this page to add new entries to machinery list </h4>
<body>
    <div class="entriesBox" id="parentNode">
        <div role="row" class="buttonPanel">
            <a hidden="hidden" id="interfaceLib">@interfaces</a>
            @using (Html.BeginForm())
            {
                <a>Collection Name:</a>
                <input name="userInput" type="text" class="collectionName" id="collectionName" value="Collection" />
                <textarea name="userData" id="userData" hidden="hidden" style="white-space:pre"></textarea>
                <button asp-page-handler="DoWork"  id="okButt" class="entryButton">OK</button>
                
            }
                <button class="entryButton" id="cancelButt">Cancel</button>
                <button class="entryButton" id="rowAddButt">Add option row </button>
            </div>
            <div role="row">

                <a>Category</a>
                <select id="categoryOptions">
                </select>
            </div>
            <div role="row">
                <a>Manufacturer</a>
                <input id="manufacturerName" required />
            </div>
            <div role="row">
                <a>Machine name</a>
                <input id="machineName" required />
            </div>

            <div class="optionalData" id="optionalData">
            </div>
        </div>
    </body>

WebAppNetCore/Pages/Index.cshtml
@page
@using MongoDB.Bson
@using MongoDB.Driver
@using System.Xml
@using Newtonsoft.Json
@using WebAppNetCore;
@using WebAppNetCore.wwwroot.Models.DataModel;
@using Microsoft.Extensions.Options;
@using Microsoft.Extensions.Configuration;
@model IndexModel
@{
    ViewData["Title"] = "Test";



    string databaseNames = await GetNames();

    string interfaceFile = await GetInterfaceLib();
}
@{
    async Task<string> GetNames()
    {
        string res = "";
        var builder = new ConfigurationBuilder();
        builder.AddJsonFile("appsettings.Development.json");

        IConfiguration configuration = builder.Build();
        var constring = configuration["MyDatabaseSettings:ConnectionString"];

        var client = new MongoClient(constring);
        var db = client.GetDatabase("AMLDatabase");
        List<string> collectionNames = new List<string>();
        foreach (BsonDocument collection in db.ListCollectionsAsync().Result.ToListAsync<BsonDocument>().Result)
        {
            string name = collection["name"].AsString;
            collectionNames.Add(name);
        }
        foreach (var i in collectionNames)
        {
            res += i + "/";
        }

        return res;

    }
    async Task<string> GetInterfaceLib()
    {
        string res = "";
        var builder = new ConfigurationBuilder();
        builder.AddJsonFile("appsettings.Development.json");

        IConfiguration configuration = builder.Build();
        var constring = configuration["MyDatabaseSettings:ConnectionString"];
        var data = new DataModel();
        var client = new MongoClient(constring);
        var db = client.GetDatabase("Interfaces_Database");
        var collection = db.GetCollection<DataModel>("Base_Interface_Library");
        var results = await collection.FindAsync<DataModel>(_ => true);
        foreach (var result in results.ToList())
        {
            if (result.Data != null)
            {
                res += result.Data;
            }
        }


        return res;
    }

}

<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="description" content="">
    <title>
        InfinityAML
    </title>

    <base href="/">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!--Dependencies here-->
    <script type="importmap">
        {
            "imports": {
            "three": "./js/three/build/three.module.js",
            "three/": "./js/three",
            "xmlwriter": "./js/xmlwriter/XMLWriter.js"
                        }
            }
    </script>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>

    <script src="~/js/xmlwriter/XMLWriter.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jstree/3.2.1/themes/default/style.min.css" />
    <!---------------------------------------------------->
</head>
<body>
    <div style="margin:5px">

        <div role="row" class="form-content">
            <div role="row">
                @using (Html.BeginForm())
                {
                    <a> Current collection: </a>
                    <textarea id="collectionsText" hidden="hidden">@databaseNames</textarea>
                    <textarea id="interfaceLib" hidden="hidden">@interfaceFile</textarea>
                    <input id="userData" name="userData" hidden="hidden" value="XmlStrings" />
                    <select id="dataCollectionsList" onchange="getValue(this)"  onfocus="this.selectedIndex = -1;">
                        <option value="" onclick="this.selectedIndex = +1;" onmousedown="this.selectedIndex = +1;"></option>
                    </select>
                    <a hidden="hidden" id="returnedData">@Model.CollectionData</a>
                    <button asp-page-handler="NameChange" class="entryButton" id="changeButt">OK</button>
                    
                }
                
                @section Scripts{
                    <script type="text/javascript">
                        var values = document.getElementById('collectionsText').innerHTML;
                        var valuesArr = Array();
                        var selector = document.getElementById('dataCollectionsList');


                        

                        valuesArr = values.split('/');
                        valuesArr.pop();
                        valuesArr.forEach(function (f) {
                            var index = valuesArr.indexOf(f);
                            var option = document.createElement('option');
                            option.id = "option";
                            option.text = f;
                            option.value = f;
                            if (index == 0) {
                                $('#option').prop('selected', 'selected');
                            }


                            selector.appendChild(option);


                        })
                        function getValue(val) {
                            var name = document.getElementById('userData');
                            name.value = val.value;
                            console.log(name.value);
                            
                            localStorage.setItem('data', name.value);

                        }
                        function RedirectToEntry(){
                            var doc = document.getElementById('returnedData');
                            if ($(doc).text() == "" || $(doc).text() == undefined) {
                                alert('No collection selected!');
                            }
                            else{
                                window.location.replace('/EntriesManager')

                            }
                        }
                        

                    </script>

                }
                    <div class="dropdown">
                        <button class="actionButton" id="dropdownButt">File</button>
                        <div class="dropdown-content">
                            <button type=button class="actionButton" id="genAML">Generate AML</button>
                            <button type=button class="actionButton" id="clearData">Clear Data</button>
                            <button type=button class="actionButton" id="addEntry" onclick="RedirectToEntry()">Add New Entry</button>
                        </div>
                    </div>
                    <div class="dropdown">
                        <button class="actionButton" id="dropdownButt">Options</button>
                        <div class="dropdown-content" style="min-width:200px">
                            <button class="actionButton" id="boxButt" style="width:100%" >Disable bounding boxes</button>
                            <button class="actionButton" id="libButt">Exclude interface library</button>
                        </div>
                    </div>
                </div>
            </div>
            <div style="display:flex" class="content-holder">
                
                <div class="treecontainer" id="treecontainer">
                    <ul class="tree" id="tree"></ul>
                </div>
                <div id="canv"></div>
            </div>
            <div class="console-holder">
                <textarea name="Console" id="console" class="console" readonly autofocus rows="5" cols="20" wrap="hard" runat="server">

                </textarea>
            </div>
        </div>
        <!-- This script makes a tree from xml file-->
        <script src="~/js/treeview.js"></script>
        <!--This makes 3dgrid in the right side of page-->
        <script src="~/js/3dgrid.js" type="module"></script>
    </body>

WebAppNetCore/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
@using System;
@{
    var currentYear = DateTime.Now.Year;
}
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TestApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebAppNetCore.styles.css" asp-append-version="true" />
</head>
<body class ="pageBody">
    <header class="SiteHeader">
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-gray border-bottom box-shadow mb-3">
            <link rel="stylesheet" href="~/css/site.css" />
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">InfinityAML</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" hidden="hidden" asp-area="" asp-page="/EntriesManager">Entries Manager</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="footer text-muted">
        <div class="container">
            &copy; @currentYear - @(currentYear + 1) - Zhyrosh Illia
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>